spring:
  application:
    name: security-demo
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo
    username: root
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      path: /api

#  security:
#    user:
#      name: admin
#      password: ${PASSWORD}

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn